/*
	接口定义文件,用于定义一个RPC服务和配套的请求/响应数据结构,核心作用是标准化RPC通信的接口和数据格式
*/
syntax = "proto3";                                               //  指定使用proto3语法

package message;                                                 //  定义包名(命名空间),避免不同proto文件的类型命名冲突

service VarifyService {                                          // service关键字用于定义RPC服务,本质是"一组RPC方法的集合"
  rpc GetVarifyCode (GetVarifyReq) returns (GetVarifyRsp) {}     // rpc 方法名 (请求类型) returns (响应类型)
}

message GetVarifyReq {                                           // message关键字定义一个结构化数据类型(类似C++的struct),用于封装RPC通信的参数
  string email = 1;                                              // 字段格式:类型 字段名 = 字段编号;字段编号是核心,每个字段必须有唯一的数字编号,后续修改proto时(比如新增字段),只要不修改旧字段的编号,新旧版本的程序就能兼容
}

message GetVarifyRsp {
  int32 error = 1;
  string email = 2;
  string code = 3;
}

service StatusService {
    rpc GetChatServer (GetChatServerReq) returns (GetChatServerRsp) {}
	rpc Login(LoginReq) returns(LoginRsp);
}

message GetChatServerReq {
  int32 uid = 1;
}

message GetChatServerRsp {
  int32 error = 1;
  string host = 2;
  string port = 3;
  string token = 4;
}

message LoginReq{
	int32 uid = 1;
	string token= 2;
}

message LoginRsp {
	int32 error = 1;
	int32 uid = 2;
	string token = 3;
}

service ChatService {
	rpc NotifyAddFriend(AddFriendReq) returns (AddFriendRsp) {}
	rpc ReplyAddFriend(ReplyFriendReq) returns (ReplyFriendRsp) {}
	rpc SendChatMsg(SendChatMsgReq) returns (SendChatMsgRsp) {}
	rpc NotifyAuthFriend(AuthFriendReq) returns (AuthFriendRsp) {}
	rpc NotifyTextChatMsg(TextChatMsgReq) returns (TextChatMsgRsp){}
}

message AddFriendReq {
	int32  applyuid = 1;
	string name = 2;
	string desc = 3;
	int32  touid = 4;
}

message AddFriendRsp {
	int32 error = 1;
	int32 applyuid = 2;
	int32 touid = 3;
}

message ReplyFriendReq {
	int32 replyuid = 1;
	bool  agree = 2;
	int32 touid = 3;
}

message ReplyFriendRsp {
	int32 error = 1;
	int32 replyuid = 2;
	int32 touid = 3;
}

message SendChatMsgReq{
		int32 fromuid = 1;
		int32 touid = 2;
		string message = 3;
}

message SendChatMsgRsp{
		int32 error = 1;
		int32 fromuid = 2;
		int32 touid = 3;
}

message AuthFriendReq{
	int32 fromuid = 1;
	int32 touid = 2;
}

message AuthFriendRsp{
	int32 error = 1;
	int32 fromuid = 2;
	int32 touid = 3;
}

message TextChatMsgReq {
	int32 fromuid = 1;
    int32 touid = 2;
	repeated TextChatData textmsgs = 3; // repeated的作用是定义重复字段,类似于其他编程语言中的数组或列表,表示该字段可以包含0个或多个相同类型的值，允许数据重复出现
}

message TextChatData{
	string msgid = 1;
	string msgcontent = 2;
}

message TextChatMsgRsp {
	int32 error = 1;
	int32 fromuid = 2;
	int32 touid = 3; 
	repeated TextChatData textmsgs = 4;
}

